---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: "node-build-action"
description: "Setup Node.js and build a project (with npm or yarn)"

inputs:
  # Optional
  NODE_VERSION:
    description: "Node.js version to use for build/install"
    required: false
    default: 22
  BUILD_TOOL:
    description: "Tool used to perform the build [npm|yarn]"
    required: false
    default: "npm"
  PATH_PREFIX:
    description: "Path/directory to Node.js project code"
    required: false
    type: string
  NPM_FLAGS:
    description: "Flags to pass to npm"
    required: false
    type: string
    default: "--omit=dev"
  YARN_FLAGS:
    description: "Flags to pass to yarn"
    required: false
    type: string
    default: "--prod"

runs:
  using: "composite"
  steps:
    - name: "Setup action/environment"
      shell: bash
      run: |
        # Setup action/environment
        # Handle path_prefix input consistently and when absent
        path_prefix="${{ inputs.PATH_PREFIX }}"
        if [ -z "$path_prefix" ]; then
          # Set current directory as path prefix
          path_prefix="."
        else
          # Strip any trailing slash in provided path
          path_prefix="${path_prefix%/}"
        fi
        # Verify is a valid directory path
        if [ ! -d "$path_prefix" ]; then
          echo "Error: invalid path/prefix to project directory ❌"; exit 1
        fi
        echo "path_prefix=$path_prefix" >> "$GITHUB_ENV"

    - name: "Check for: package.json"
      id: path-check
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/path-check-action@ef6cb64d8851552e1290d7e535d00380ce1f5112 # v0.1.2
      with:
        path: "${{ env.path_prefix }}/package.json"

    - name: "Validate action/environment"
      shell: bash
      run: |
        # Validate action/environment
        echo "# Node.js Build/Install 🛠️" >> "$GITHUB_STEP_SUMMARY"
        if [ -n "${{ env.path_prefix }}" ] && \
          [ ! -d "${{ env.path_prefix }}" ]; then
          echo "Error: invalid path to project directory ❌"
          echo "Error: invalid path to project directory ❌" \
            >> "$GITHUB_STEP_SUMMARY"
          echo "Path: ${{ env.path_prefix }}"
          exit 1
        fi
        if [ "${{ steps.path-check.outputs.type }}" != 'file' ]; then
          echo "Error: No Node.js package.json file was found ❌"
          echo "Error: No Node.js package.json file was found ❌" \
            >> "$GITHUB_STEP_SUMMARY"
          exit 1
        fi
        echo "Node.js build/install tool: ${{ inputs.build_tool }} 💬"
        echo "Node.js build/install tool: ${{ inputs.build_tool }} 💬" \
          >> "$GITHUB_STEP_SUMMARY"

    - name: "Setup Node.js"
      id: setup-node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node_version }}

    - name: "Build with NPM"
      shell: bash
      if: inputs.build_tool == 'npm'
      run:
        # Build/install project with NPM
        npm install --prefix "${{ env.path_prefix }}" ${{ inputs.npm_flags }}

    - name: "Build with Yarn"
      shell: bash
      if: inputs.build_tool == 'yarn'
      run:
        # Build/install project with Yarn
        yarn install --cwd="${{ env.path_prefix }}" ${{ inputs.yarn_flags }}
